/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
        // Wedding luxury palette
        gold: {
          DEFAULT: '#D4AF37',
          light: '#E8D48B',
          dark: '#B8960C',
          50: '#FDF9E7',
          100: '#FAF0C0',
          200: '#F5E07A',
          300: '#E8D48B',
          400: '#D4AF37',
          500: '#B8960C',
          600: '#9A7D0A',
          700: '#7D6408',
          800: '#5F4B06',
          900: '#3D3004',
        },
        crimson: {
          DEFAULT: '#8B0000',
          light: '#C41E3A',
          50: '#FFF0F0',
          100: '#FFD6D6',
          200: '#FFA8A8',
          300: '#FF7070',
          400: '#E83030',
          500: '#C41E3A',
          600: '#8B0000',
          700: '#6B0000',
          800: '#4A0000',
          900: '#2D0000',
        },
        ivory: {
          DEFAULT: '#FFFFF0',
          dark: '#F5F5DC',
          50: '#FFFFF0',
          100: '#FEFEE0',
          200: '#FDFDC0',
          300: '#FBFB9A',
          400: '#F8F870',
          500: '#F5F5DC',
          600: '#E8E8C0',
          700: '#D4D4A0',
          800: '#B8B880',
          900: '#909060',
        },
        charcoal: {
          DEFAULT: '#36454F',
          light: '#4A5568',
          50: '#F0F4F6',
          100: '#D9E4E8',
          200: '#B3C8D0',
          300: '#8DADB8',
          400: '#6791A0',
          500: '#4A5568',
          600: '#36454F',
          700: '#2A3540',
          800: '#1E2730',
          900: '#121820',
        },
      },
      fontFamily: {
        serif: ['Cormorant Garamond', 'Playfair Display', 'Georgia', 'serif'],
        display: ['Playfair Display', 'Georgia', 'serif'],
        cinzel: ['Cinzel', 'serif'],
        script: ['Great Vibes', 'cursive'],
        sans: ['Open Sans', 'system-ui', 'sans-serif'],
        elegant: ['Montserrat', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      boxShadow: {
        'luxury': '0 4px 20px rgba(212, 175, 55, 0.15), 0 1px 4px rgba(212, 175, 55, 0.1)',
        'luxury-lg': '0 8px 40px rgba(212, 175, 55, 0.2), 0 2px 8px rgba(212, 175, 55, 0.15)',
        'crimson': '0 4px 20px rgba(139, 0, 0, 0.15)',
        'card': '0 2px 15px rgba(54, 69, 79, 0.08)',
        'card-hover': '0 8px 30px rgba(54, 69, 79, 0.15)',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(30px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        shimmer: 'shimmer 2s infinite',
        'fade-in-up': 'fadeInUp 0.8s ease-out forwards',
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [
    require('tailwindcss-animate'),
    require('@tailwindcss/typography'),
  ],
};
