/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        /* Custom design tokens */
        ivory: {
          DEFAULT: 'var(--ivory)',
          dark: 'var(--ivory-dark)',
        },
        gold: {
          DEFAULT: 'var(--gold)',
          light: 'var(--gold-light)',
          dark: 'var(--gold-dark)',
          50: 'oklch(0.97 0.01 80)',
          100: 'oklch(0.94 0.02 80)',
          200: 'oklch(0.88 0.06 80)',
          300: 'oklch(0.82 0.09 78)',
          400: 'oklch(0.76 0.11 76)',
          500: 'oklch(0.72 0.12 75)',
          600: 'oklch(0.65 0.14 72)',
          700: 'oklch(0.55 0.18 45)',
          800: 'oklch(0.45 0.16 45)',
          900: 'oklch(0.35 0.12 45)',
        },
        crimson: {
          DEFAULT: 'var(--crimson)',
          light: 'var(--crimson-light)',
          50: 'oklch(0.97 0.01 15)',
          100: 'oklch(0.93 0.03 15)',
          200: 'oklch(0.85 0.07 15)',
          300: 'oklch(0.75 0.12 20)',
          400: 'oklch(0.65 0.18 25)',
          500: 'oklch(0.55 0.20 25)',
          600: 'oklch(0.45 0.20 25)',
          700: 'oklch(0.38 0.18 25)',
          800: 'oklch(0.30 0.14 25)',
          900: 'oklch(0.22 0.10 25)',
        },
        rose: {
          DEFAULT: 'var(--rose)',
          light: 'var(--rose-light)',
          50: 'oklch(0.97 0.01 10)',
          100: 'oklch(0.93 0.03 10)',
          200: 'oklch(0.88 0.06 15)',
          300: 'oklch(0.82 0.08 15)',
          400: 'oklch(0.75 0.10 15)',
          500: 'oklch(0.68 0.12 15)',
          600: 'oklch(0.60 0.14 15)',
          700: 'oklch(0.50 0.14 15)',
          800: 'oklch(0.40 0.12 15)',
          900: 'oklch(0.30 0.10 15)',
        },
        charcoal: {
          DEFAULT: 'var(--charcoal)',
          light: 'var(--charcoal-light)',
          50: 'oklch(0.97 0.005 60)',
          100: 'oklch(0.93 0.008 60)',
          200: 'oklch(0.85 0.01 60)',
          300: 'oklch(0.72 0.015 60)',
          400: 'oklch(0.58 0.02 60)',
          500: 'oklch(0.45 0.025 60)',
          600: 'oklch(0.35 0.025 60)',
          700: 'oklch(0.28 0.02 60)',
          800: 'oklch(0.22 0.015 60)',
          900: 'oklch(0.15 0.01 60)',
        },
      },
      fontFamily: {
        heading: ['"Playfair Display"', '"Cormorant Garamond"', 'Georgia', 'serif'],
        body: ['Lato', 'Montserrat', 'sans-serif'],
        script: ['"Great Vibes"', '"Dancing Script"', 'cursive'],
        serif: ['"Cormorant Garamond"', '"EB Garamond"', 'Georgia', 'serif'],
        sans: ['Lato', 'Montserrat', 'system-ui', 'sans-serif'],
        display: ['"Cinzel"', '"Playfair Display"', 'serif'],
        mono: ['"Josefin Sans"', 'monospace'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      boxShadow: {
        'luxury': '0 4px 24px -4px oklch(0.55 0.18 45 / 0.15), 0 1px 4px oklch(0.55 0.18 45 / 0.08)',
        'luxury-lg': '0 8px 40px -8px oklch(0.55 0.18 45 / 0.20), 0 2px 8px oklch(0.55 0.18 45 / 0.10)',
        'gold': '0 0 20px oklch(0.72 0.12 75 / 0.30)',
        'card': '0 2px 16px oklch(0.18 0.02 60 / 0.08)',
        'card-hover': '0 8px 32px oklch(0.18 0.02 60 / 0.12)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(30px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        slideInUp: {
          from: { opacity: '0', transform: 'translateY(40px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          from: { opacity: '0', transform: 'scale(0.9)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        petalFall: {
          '0%': { transform: 'translateY(-10px) rotate(0deg) translateX(0px)', opacity: '0' },
          '10%': { opacity: '0.7' },
          '90%': { opacity: '0.5' },
          '100%': { transform: 'translateY(100vh) rotate(360deg) translateX(50px)', opacity: '0' },
        },
        petalFallAlt: {
          '0%': { transform: 'translateY(-10px) rotate(0deg) translateX(0px)', opacity: '0' },
          '10%': { opacity: '0.7' },
          '90%': { opacity: '0.5' },
          '100%': { transform: 'translateY(100vh) rotate(-360deg) translateX(-50px)', opacity: '0' },
        },
        diyaGlow: {
          '0%': { filter: 'drop-shadow(0 0 4px oklch(0.72 0.12 75))', opacity: '0.8' },
          '100%': { filter: 'drop-shadow(0 0 12px oklch(0.72 0.12 75)) drop-shadow(0 0 24px oklch(0.55 0.18 45))', opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        cinematicReveal: {
          '0%': { opacity: '0', transform: 'scale(1.05) translateY(20px)', filter: 'blur(4px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)', filter: 'blur(0)' },
        },
        elegantFade: {
          '0%': { opacity: '0', transform: 'translateY(16px)', letterSpacing: '0.2em' },
          '100%': { opacity: '1', transform: 'translateY(0)', letterSpacing: 'normal' },
        },
        parallaxFloat: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '33%': { transform: 'translateY(-8px) rotate(1deg)' },
          '66%': { transform: 'translateY(4px) rotate(-1deg)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fadeIn 0.6s ease forwards',
        'fade-in-up': 'fadeInUp 0.7s ease forwards',
        'slide-in-up': 'slideInUp 0.6s ease forwards',
        'scale-in': 'scaleIn 0.5s ease forwards',
        'petal-fall': 'petalFall linear infinite',
        'petal-fall-alt': 'petalFallAlt linear infinite',
        'diya-glow': 'diyaGlow 2s ease-in-out infinite alternate',
        'float-gentle': 'float 6s ease-in-out infinite',
        'shimmer': 'shimmer 1.5s infinite',
        'cinematic-reveal': 'cinematicReveal 1.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'elegant-fade': 'elegantFade 1.5s ease forwards',
        'parallax-float': 'parallaxFloat 8s ease-in-out infinite',
      },
    },
  },
  plugins: [
    require('tailwindcss-animate'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/container-queries'),
  ],
};
