/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Event {
    id: string;
    title: string;
    venue: string;
    date: string;
    invitationId: string;
    time: string;
    description: string;
    eventType: EventType;
}
export interface Invitation {
    id: string;
    weddingDate: string;
    invitationMessage: string;
    weddingTime: string;
    isPublished: boolean;
    venueAddress: string;
    createdAt: bigint;
    googleMapsLink: string;
    fontChoice: string;
    updatedAt: bigint;
    selectedTemplate: string;
    backgroundChoice: string;
    brideName: string;
    groomName: string;
    venueName: string;
    familyDetails: string;
    colorScheme: string;
}
export interface RSVPEntry {
    id: string;
    guestCount: bigint;
    invitationId: string;
    submittedAt: bigint;
    guestName: string;
    message: string;
    attending: boolean;
    guestPhone: string;
}
export interface BackgroundMusic {
    id: string;
    musicUrl: string;
    autoPlay: boolean;
    invitationId: string;
    uploadedAt: bigint;
}
export interface Photo {
    id: string;
    invitationId: string;
    imageUrl: string;
    uploadedAt: bigint;
}
export enum EventType {
    mehndi = "mehndi",
    sangeet = "sangeet",
    haldi = "haldi",
    custom = "custom",
    wedding = "wedding",
    reception = "reception"
}
export interface backendInterface {
    addEvent(invitationId: string, eventId: string, title: string, date: string, time: string, venue: string, description: string, eventType: EventType): Promise<Event>;
    addPhoto(invitationId: string, photoId: string, imageUrl: string): Promise<Photo>;
    createInvitation(slug: string, brideName: string, groomName: string, weddingDate: string, weddingTime: string, venueName: string, venueAddress: string, googleMapsLink: string, familyDetails: string, invitationMessage: string, selectedTemplate: string, colorScheme: string, fontChoice: string, backgroundChoice: string): Promise<Invitation>;
    deleteEvent(eventId: string): Promise<void>;
    deleteInvitation(slug: string): Promise<void>;
    deletePhoto(photoId: string): Promise<void>;
    getAllInvitations(): Promise<Array<Invitation>>;
    getBackgroundMusic(invitationId: string): Promise<Array<BackgroundMusic>>;
    getEventsByInvitation(invitationId: string): Promise<Array<Event>>;
    getInvitationBySlug(slug: string): Promise<Invitation>;
    getPhotosByInvitation(invitationId: string): Promise<Array<Photo>>;
    getRSVPsByInvitation(invitationId: string): Promise<Array<RSVPEntry>>;
    publishInvitation(slug: string): Promise<Invitation>;
    setBackgroundMusic(invitationId: string, musicId: string, musicUrl: string, autoPlay: boolean): Promise<BackgroundMusic>;
    submitRSVP(invitationId: string, rsvpId: string, guestName: string, guestPhone: string, attending: boolean, guestCount: bigint, message: string): Promise<RSVPEntry>;
    updateEvent(eventId: string, title: string, date: string, time: string, venue: string, description: string, eventType: EventType): Promise<Event>;
    updateInvitation(slug: string, brideName: string, groomName: string, weddingDate: string, weddingTime: string, venueName: string, venueAddress: string, googleMapsLink: string, familyDetails: string, invitationMessage: string, selectedTemplate: string, colorScheme: string, fontChoice: string, backgroundChoice: string): Promise<Invitation>;
}
import type { Event as _Event, EventType as _EventType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEvent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: EventType): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_EventType_n1(this._uploadFile, this._downloadFile, arg7));
                return from_candid_Event_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_EventType_n1(this._uploadFile, this._downloadFile, arg7));
            return from_candid_Event_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPhoto(arg0: string, arg1: string, arg2: string): Promise<Photo> {
        if (this.processError) {
            try {
                const result = await this.actor.addPhoto(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPhoto(arg0, arg1, arg2);
            return result;
        }
    }
    async createInvitation(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string, arg11: string, arg12: string, arg13: string): Promise<Invitation> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvitation(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvitation(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
            return result;
        }
    }
    async deleteEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteInvitation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvitation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvitation(arg0);
            return result;
        }
    }
    async deletePhoto(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePhoto(arg0);
            return result;
        }
    }
    async getAllInvitations(): Promise<Array<Invitation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvitations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvitations();
            return result;
        }
    }
    async getBackgroundMusic(arg0: string): Promise<Array<BackgroundMusic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBackgroundMusic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBackgroundMusic(arg0);
            return result;
        }
    }
    async getEventsByInvitation(arg0: string): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByInvitation(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByInvitation(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvitationBySlug(arg0: string): Promise<Invitation> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvitationBySlug(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvitationBySlug(arg0);
            return result;
        }
    }
    async getPhotosByInvitation(arg0: string): Promise<Array<Photo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotosByInvitation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotosByInvitation(arg0);
            return result;
        }
    }
    async getRSVPsByInvitation(arg0: string): Promise<Array<RSVPEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRSVPsByInvitation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRSVPsByInvitation(arg0);
            return result;
        }
    }
    async publishInvitation(arg0: string): Promise<Invitation> {
        if (this.processError) {
            try {
                const result = await this.actor.publishInvitation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishInvitation(arg0);
            return result;
        }
    }
    async setBackgroundMusic(arg0: string, arg1: string, arg2: string, arg3: boolean): Promise<BackgroundMusic> {
        if (this.processError) {
            try {
                const result = await this.actor.setBackgroundMusic(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBackgroundMusic(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: string, arg2: string, arg3: string, arg4: boolean, arg5: bigint, arg6: string): Promise<RSVPEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateEvent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: EventType): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_EventType_n1(this._uploadFile, this._downloadFile, arg6));
                return from_candid_Event_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_EventType_n1(this._uploadFile, this._downloadFile, arg6));
            return from_candid_Event_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateInvitation(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string, arg11: string, arg12: string, arg13: string): Promise<Invitation> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvitation(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvitation(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
            return result;
        }
    }
}
function from_candid_EventType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    venue: string;
    date: string;
    invitationId: string;
    time: string;
    description: string;
    eventType: _EventType;
}): {
    id: string;
    title: string;
    venue: string;
    date: string;
    invitationId: string;
    time: string;
    description: string;
    eventType: EventType;
} {
    return {
        id: value.id,
        title: value.title,
        venue: value.venue,
        date: value.date,
        invitationId: value.invitationId,
        time: value.time,
        description: value.description,
        eventType: from_candid_EventType_n5(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mehndi: null;
} | {
    sangeet: null;
} | {
    haldi: null;
} | {
    custom: null;
} | {
    wedding: null;
} | {
    reception: null;
}): EventType {
    return "mehndi" in value ? EventType.mehndi : "sangeet" in value ? EventType.sangeet : "haldi" in value ? EventType.haldi : "custom" in value ? EventType.custom : "wedding" in value ? EventType.wedding : "reception" in value ? EventType.reception : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n3(_uploadFile, _downloadFile, x));
}
function to_candid_EventType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): {
    mehndi: null;
} | {
    sangeet: null;
} | {
    haldi: null;
} | {
    custom: null;
} | {
    wedding: null;
} | {
    reception: null;
} {
    return value == EventType.mehndi ? {
        mehndi: null
    } : value == EventType.sangeet ? {
        sangeet: null
    } : value == EventType.haldi ? {
        haldi: null
    } : value == EventType.custom ? {
        custom: null
    } : value == EventType.wedding ? {
        wedding: null
    } : value == EventType.reception ? {
        reception: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
