/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EventType = IDL.Variant({
  'mehndi' : IDL.Null,
  'sangeet' : IDL.Null,
  'haldi' : IDL.Null,
  'custom' : IDL.Null,
  'wedding' : IDL.Null,
  'reception' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'date' : IDL.Text,
  'invitationId' : IDL.Text,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'eventType' : EventType,
});
export const Photo = IDL.Record({
  'id' : IDL.Text,
  'invitationId' : IDL.Text,
  'imageUrl' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const ThemeConfig = IDL.Record({
  'fontChoice' : IDL.Text,
  'backgroundChoice' : IDL.Text,
  'template' : IDL.Text,
  'colorScheme' : IDL.Text,
});
export const Invitation = IDL.Record({
  'id' : IDL.Text,
  'weddingDate' : IDL.Text,
  'invitationMessage' : IDL.Text,
  'weddingTime' : IDL.Text,
  'isPublished' : IDL.Bool,
  'venueAddress' : IDL.Text,
  'createdAt' : IDL.Int,
  'googleMapsLink' : IDL.Text,
  'fontChoice' : IDL.Text,
  'updatedAt' : IDL.Int,
  'selectedTemplate' : IDL.Text,
  'savedThemes' : IDL.Vec(ThemeConfig),
  'backgroundChoice' : IDL.Text,
  'brideName' : IDL.Text,
  'groomName' : IDL.Text,
  'venueName' : IDL.Text,
  'familyDetails' : IDL.Text,
  'colorScheme' : IDL.Text,
});
export const BackgroundMusic = IDL.Record({
  'id' : IDL.Text,
  'musicUrl' : IDL.Text,
  'autoPlay' : IDL.Bool,
  'invitationId' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const RSVPEntry = IDL.Record({
  'id' : IDL.Text,
  'guestCount' : IDL.Nat,
  'invitationId' : IDL.Text,
  'submittedAt' : IDL.Int,
  'guestName' : IDL.Text,
  'message' : IDL.Text,
  'attending' : IDL.Bool,
  'guestPhone' : IDL.Text,
});
export const RSVPStats = IDL.Record({
  'totalConfirmedGuests' : IDL.Nat,
  'totalResponses' : IDL.Nat,
  'totalDeclined' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        EventType,
      ],
      [Event],
      [],
    ),
  'addPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Photo], []),
  'createInvitation' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Invitation],
      [],
    ),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'deleteInvitation' : IDL.Func([IDL.Text], [], []),
  'deletePhoto' : IDL.Func([IDL.Text], [], []),
  'deleteThemeVariant' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAllInvitations' : IDL.Func([], [IDL.Vec(Invitation)], ['query']),
  'getBackgroundMusic' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BackgroundMusic)],
      ['query'],
    ),
  'getEventsByInvitation' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
  'getInvitationBySlug' : IDL.Func([IDL.Text], [Invitation], []),
  'getPhotosByInvitation' : IDL.Func([IDL.Text], [IDL.Vec(Photo)], ['query']),
  'getRSVPsByInvitation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RSVPEntry)],
      ['query'],
    ),
  'getRSVPsStats' : IDL.Func([IDL.Text], [RSVPStats], ['query']),
  'getThemeVariants' : IDL.Func([IDL.Text], [IDL.Vec(ThemeConfig)], ['query']),
  'publishInvitation' : IDL.Func([IDL.Text], [Invitation], []),
  'saveThemeVariant' : IDL.Func([IDL.Text, ThemeConfig], [], []),
  'setBackgroundMusic' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [BackgroundMusic],
      [],
    ),
  'submitRSVP' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat, IDL.Text],
      [RSVPEntry],
      [],
    ),
  'updateEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, EventType],
      [Event],
      [],
    ),
  'updateInvitation' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Invitation],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EventType = IDL.Variant({
    'mehndi' : IDL.Null,
    'sangeet' : IDL.Null,
    'haldi' : IDL.Null,
    'custom' : IDL.Null,
    'wedding' : IDL.Null,
    'reception' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'date' : IDL.Text,
    'invitationId' : IDL.Text,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'eventType' : EventType,
  });
  const Photo = IDL.Record({
    'id' : IDL.Text,
    'invitationId' : IDL.Text,
    'imageUrl' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const ThemeConfig = IDL.Record({
    'fontChoice' : IDL.Text,
    'backgroundChoice' : IDL.Text,
    'template' : IDL.Text,
    'colorScheme' : IDL.Text,
  });
  const Invitation = IDL.Record({
    'id' : IDL.Text,
    'weddingDate' : IDL.Text,
    'invitationMessage' : IDL.Text,
    'weddingTime' : IDL.Text,
    'isPublished' : IDL.Bool,
    'venueAddress' : IDL.Text,
    'createdAt' : IDL.Int,
    'googleMapsLink' : IDL.Text,
    'fontChoice' : IDL.Text,
    'updatedAt' : IDL.Int,
    'selectedTemplate' : IDL.Text,
    'savedThemes' : IDL.Vec(ThemeConfig),
    'backgroundChoice' : IDL.Text,
    'brideName' : IDL.Text,
    'groomName' : IDL.Text,
    'venueName' : IDL.Text,
    'familyDetails' : IDL.Text,
    'colorScheme' : IDL.Text,
  });
  const BackgroundMusic = IDL.Record({
    'id' : IDL.Text,
    'musicUrl' : IDL.Text,
    'autoPlay' : IDL.Bool,
    'invitationId' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const RSVPEntry = IDL.Record({
    'id' : IDL.Text,
    'guestCount' : IDL.Nat,
    'invitationId' : IDL.Text,
    'submittedAt' : IDL.Int,
    'guestName' : IDL.Text,
    'message' : IDL.Text,
    'attending' : IDL.Bool,
    'guestPhone' : IDL.Text,
  });
  const RSVPStats = IDL.Record({
    'totalConfirmedGuests' : IDL.Nat,
    'totalResponses' : IDL.Nat,
    'totalDeclined' : IDL.Nat,
  });
  
  return IDL.Service({
    'addEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          EventType,
        ],
        [Event],
        [],
      ),
    'addPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Photo], []),
    'createInvitation' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Invitation],
        [],
      ),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'deleteInvitation' : IDL.Func([IDL.Text], [], []),
    'deletePhoto' : IDL.Func([IDL.Text], [], []),
    'deleteThemeVariant' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAllInvitations' : IDL.Func([], [IDL.Vec(Invitation)], ['query']),
    'getBackgroundMusic' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BackgroundMusic)],
        ['query'],
      ),
    'getEventsByInvitation' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
    'getInvitationBySlug' : IDL.Func([IDL.Text], [Invitation], []),
    'getPhotosByInvitation' : IDL.Func([IDL.Text], [IDL.Vec(Photo)], ['query']),
    'getRSVPsByInvitation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RSVPEntry)],
        ['query'],
      ),
    'getRSVPsStats' : IDL.Func([IDL.Text], [RSVPStats], ['query']),
    'getThemeVariants' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ThemeConfig)],
        ['query'],
      ),
    'publishInvitation' : IDL.Func([IDL.Text], [Invitation], []),
    'saveThemeVariant' : IDL.Func([IDL.Text, ThemeConfig], [], []),
    'setBackgroundMusic' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [BackgroundMusic],
        [],
      ),
    'submitRSVP' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat, IDL.Text],
        [RSVPEntry],
        [],
      ),
    'updateEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, EventType],
        [Event],
        [],
      ),
    'updateInvitation' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Invitation],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };