/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BackgroundMusic {
  'id' : string,
  'musicUrl' : string,
  'autoPlay' : boolean,
  'invitationId' : string,
  'uploadedAt' : bigint,
}
export interface Event {
  'id' : string,
  'title' : string,
  'venue' : string,
  'date' : string,
  'invitationId' : string,
  'time' : string,
  'description' : string,
  'eventType' : EventType,
}
export interface EventInput {
  'id' : string,
  'title' : string,
  'venue' : string,
  'date' : string,
  'invitationId' : string,
  'time' : string,
  'description' : string,
  'eventType' : string,
}
export type EventType = { 'mehndi' : null } |
  { 'sangeet' : null } |
  { 'haldi' : null } |
  { 'custom' : null } |
  { 'wedding' : null } |
  { 'reception' : null };
export type ExternalBlob = Uint8Array;
export interface Invitation {
  'id' : string,
  'weddingDate' : string,
  'invitationMessage' : string,
  'groomPhoto' : [] | [ExternalBlob],
  'weddingTime' : string,
  'isPublished' : boolean,
  'venueAddress' : string,
  'createdAt' : bigint,
  'googleMapsLink' : string,
  'fontChoice' : string,
  'updatedAt' : bigint,
  'selectedTemplate' : string,
  'savedThemes' : Array<ThemeConfig>,
  'backgroundChoice' : string,
  'brideName' : string,
  'groomName' : string,
  'venueName' : string,
  'familyDetails' : string,
  'bridePhoto' : [] | [ExternalBlob],
  'colorScheme' : string,
}
export interface InvitationInput {
  'weddingDate' : string,
  'invitationMessage' : string,
  'weddingTime' : string,
  'venueAddress' : string,
  'slug' : string,
  'googleMapsLink' : string,
  'fontChoice' : string,
  'selectedTemplate' : string,
  'backgroundChoice' : string,
  'brideName' : string,
  'groomName' : string,
  'venueName' : string,
  'familyDetails' : string,
  'colorScheme' : string,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface Photo {
  'id' : string,
  'invitationId' : string,
  'imageUrl' : string,
  'uploadedAt' : bigint,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface RSVPEntry {
  'id' : string,
  'guestCount' : bigint,
  'invitationId' : string,
  'submittedAt' : bigint,
  'guestName' : string,
  'message' : string,
  'attending' : boolean,
  'guestPhone' : string,
}
export interface RSVPInput {
  'rsvpId' : string,
  'guestCount' : bigint,
  'invitationId' : string,
  'guestName' : string,
  'message' : string,
  'attending' : boolean,
  'guestPhone' : string,
}
export interface RSVPStats {
  'totalConfirmedGuests' : bigint,
  'totalResponses' : bigint,
  'totalDeclined' : bigint,
}
export interface ThemeConfig {
  'name' : string,
  'fontChoice' : string,
  'backgroundChoice' : string,
  'template' : string,
  'colorScheme' : string,
}
export type Time = bigint;
export interface UpdateEventInput {
  'title' : string,
  'venue' : string,
  'date' : string,
  'time' : string,
  'description' : string,
  'eventType' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPhoto' : ActorMethod<[string, string, string], Photo>,
  'addPhotos' : ActorMethod<
    [string, [] | [ExternalBlob], [] | [ExternalBlob]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEvent' : ActorMethod<[EventInput], Event>,
  'createInvitation' : ActorMethod<[InvitationInput], Invitation>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'deleteInvitation' : ActorMethod<[string], undefined>,
  'deletePhoto' : ActorMethod<[string], undefined>,
  'deleteThemeVariant' : ActorMethod<[string, bigint], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllInvitations' : ActorMethod<[], Array<Invitation>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getBackgroundMusic' : ActorMethod<[string], Array<BackgroundMusic>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEventsByInvitation' : ActorMethod<[string], Array<Event>>,
  'getInvitationBySlug' : ActorMethod<[string], Invitation>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getPhotosByInvitation' : ActorMethod<[string], Array<Photo>>,
  'getRSVPsByInvitation' : ActorMethod<[string], Array<RSVPEntry>>,
  'getRSVPsStats' : ActorMethod<[string], RSVPStats>,
  'getThemeVariants' : ActorMethod<[string], Array<ThemeConfig>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishInvitation' : ActorMethod<[string], Invitation>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveThemeVariant' : ActorMethod<[string, ThemeConfig], undefined>,
  'setBackgroundMusic' : ActorMethod<
    [string, string, string, boolean],
    BackgroundMusic
  >,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'submitWeddingInvitationRSVP' : ActorMethod<[RSVPInput], RSVPEntry>,
  'updateEvent' : ActorMethod<[string, UpdateEventInput], Event>,
  'updateInvitation' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    Invitation
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];