/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Photo = IDL.Record({
  'id' : IDL.Text,
  'invitationId' : IDL.Text,
  'imageUrl' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EventInput = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'date' : IDL.Text,
  'invitationId' : IDL.Text,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'eventType' : IDL.Text,
});
export const EventType = IDL.Variant({
  'mehndi' : IDL.Null,
  'sangeet' : IDL.Null,
  'haldi' : IDL.Null,
  'custom' : IDL.Null,
  'wedding' : IDL.Null,
  'reception' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'date' : IDL.Text,
  'invitationId' : IDL.Text,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'eventType' : EventType,
});
export const InvitationInput = IDL.Record({
  'weddingDate' : IDL.Text,
  'invitationMessage' : IDL.Text,
  'weddingTime' : IDL.Text,
  'venueAddress' : IDL.Text,
  'slug' : IDL.Text,
  'googleMapsLink' : IDL.Text,
  'fontChoice' : IDL.Text,
  'selectedTemplate' : IDL.Text,
  'backgroundChoice' : IDL.Text,
  'brideName' : IDL.Text,
  'groomName' : IDL.Text,
  'venueName' : IDL.Text,
  'familyDetails' : IDL.Text,
  'colorScheme' : IDL.Text,
});
export const ThemeConfig = IDL.Record({
  'name' : IDL.Text,
  'fontChoice' : IDL.Text,
  'backgroundChoice' : IDL.Text,
  'template' : IDL.Text,
  'colorScheme' : IDL.Text,
});
export const Invitation = IDL.Record({
  'id' : IDL.Text,
  'weddingDate' : IDL.Text,
  'invitationMessage' : IDL.Text,
  'groomPhoto' : IDL.Opt(ExternalBlob),
  'weddingTime' : IDL.Text,
  'isPublished' : IDL.Bool,
  'venueAddress' : IDL.Text,
  'createdAt' : IDL.Int,
  'googleMapsLink' : IDL.Text,
  'fontChoice' : IDL.Text,
  'updatedAt' : IDL.Int,
  'selectedTemplate' : IDL.Text,
  'savedThemes' : IDL.Vec(ThemeConfig),
  'backgroundChoice' : IDL.Text,
  'brideName' : IDL.Text,
  'groomName' : IDL.Text,
  'venueName' : IDL.Text,
  'familyDetails' : IDL.Text,
  'bridePhoto' : IDL.Opt(ExternalBlob),
  'colorScheme' : IDL.Text,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const BackgroundMusic = IDL.Record({
  'id' : IDL.Text,
  'musicUrl' : IDL.Text,
  'autoPlay' : IDL.Bool,
  'invitationId' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const RSVPEntry = IDL.Record({
  'id' : IDL.Text,
  'guestCount' : IDL.Nat,
  'invitationId' : IDL.Text,
  'submittedAt' : IDL.Int,
  'guestName' : IDL.Text,
  'message' : IDL.Text,
  'attending' : IDL.Bool,
  'guestPhone' : IDL.Text,
});
export const RSVPStats = IDL.Record({
  'totalConfirmedGuests' : IDL.Nat,
  'totalResponses' : IDL.Nat,
  'totalDeclined' : IDL.Nat,
});
export const RSVPInput = IDL.Record({
  'rsvpId' : IDL.Text,
  'guestCount' : IDL.Nat,
  'invitationId' : IDL.Text,
  'guestName' : IDL.Text,
  'message' : IDL.Text,
  'attending' : IDL.Bool,
  'guestPhone' : IDL.Text,
});
export const UpdateEventInput = IDL.Record({
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'eventType' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Photo], []),
  'addPhotos' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func([EventInput], [Event], []),
  'createInvitation' : IDL.Func([InvitationInput], [Invitation], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'deleteInvitation' : IDL.Func([IDL.Text], [], []),
  'deletePhoto' : IDL.Func([IDL.Text], [], []),
  'deleteThemeVariant' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllInvitations' : IDL.Func([], [IDL.Vec(Invitation)], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getBackgroundMusic' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BackgroundMusic)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEventsByInvitation' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
  'getInvitationBySlug' : IDL.Func([IDL.Text], [Invitation], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getPhotosByInvitation' : IDL.Func([IDL.Text], [IDL.Vec(Photo)], ['query']),
  'getRSVPsByInvitation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RSVPEntry)],
      ['query'],
    ),
  'getRSVPsStats' : IDL.Func([IDL.Text], [RSVPStats], ['query']),
  'getThemeVariants' : IDL.Func([IDL.Text], [IDL.Vec(ThemeConfig)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishInvitation' : IDL.Func([IDL.Text], [Invitation], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveThemeVariant' : IDL.Func([IDL.Text, ThemeConfig], [], []),
  'setBackgroundMusic' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [BackgroundMusic],
      [],
    ),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'submitWeddingInvitationRSVP' : IDL.Func([RSVPInput], [RSVPEntry], []),
  'updateEvent' : IDL.Func([IDL.Text, UpdateEventInput], [Event], []),
  'updateInvitation' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Invitation],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Photo = IDL.Record({
    'id' : IDL.Text,
    'invitationId' : IDL.Text,
    'imageUrl' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EventInput = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'date' : IDL.Text,
    'invitationId' : IDL.Text,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const EventType = IDL.Variant({
    'mehndi' : IDL.Null,
    'sangeet' : IDL.Null,
    'haldi' : IDL.Null,
    'custom' : IDL.Null,
    'wedding' : IDL.Null,
    'reception' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'date' : IDL.Text,
    'invitationId' : IDL.Text,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'eventType' : EventType,
  });
  const InvitationInput = IDL.Record({
    'weddingDate' : IDL.Text,
    'invitationMessage' : IDL.Text,
    'weddingTime' : IDL.Text,
    'venueAddress' : IDL.Text,
    'slug' : IDL.Text,
    'googleMapsLink' : IDL.Text,
    'fontChoice' : IDL.Text,
    'selectedTemplate' : IDL.Text,
    'backgroundChoice' : IDL.Text,
    'brideName' : IDL.Text,
    'groomName' : IDL.Text,
    'venueName' : IDL.Text,
    'familyDetails' : IDL.Text,
    'colorScheme' : IDL.Text,
  });
  const ThemeConfig = IDL.Record({
    'name' : IDL.Text,
    'fontChoice' : IDL.Text,
    'backgroundChoice' : IDL.Text,
    'template' : IDL.Text,
    'colorScheme' : IDL.Text,
  });
  const Invitation = IDL.Record({
    'id' : IDL.Text,
    'weddingDate' : IDL.Text,
    'invitationMessage' : IDL.Text,
    'groomPhoto' : IDL.Opt(ExternalBlob),
    'weddingTime' : IDL.Text,
    'isPublished' : IDL.Bool,
    'venueAddress' : IDL.Text,
    'createdAt' : IDL.Int,
    'googleMapsLink' : IDL.Text,
    'fontChoice' : IDL.Text,
    'updatedAt' : IDL.Int,
    'selectedTemplate' : IDL.Text,
    'savedThemes' : IDL.Vec(ThemeConfig),
    'backgroundChoice' : IDL.Text,
    'brideName' : IDL.Text,
    'groomName' : IDL.Text,
    'venueName' : IDL.Text,
    'familyDetails' : IDL.Text,
    'bridePhoto' : IDL.Opt(ExternalBlob),
    'colorScheme' : IDL.Text,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const BackgroundMusic = IDL.Record({
    'id' : IDL.Text,
    'musicUrl' : IDL.Text,
    'autoPlay' : IDL.Bool,
    'invitationId' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const RSVPEntry = IDL.Record({
    'id' : IDL.Text,
    'guestCount' : IDL.Nat,
    'invitationId' : IDL.Text,
    'submittedAt' : IDL.Int,
    'guestName' : IDL.Text,
    'message' : IDL.Text,
    'attending' : IDL.Bool,
    'guestPhone' : IDL.Text,
  });
  const RSVPStats = IDL.Record({
    'totalConfirmedGuests' : IDL.Nat,
    'totalResponses' : IDL.Nat,
    'totalDeclined' : IDL.Nat,
  });
  const RSVPInput = IDL.Record({
    'rsvpId' : IDL.Text,
    'guestCount' : IDL.Nat,
    'invitationId' : IDL.Text,
    'guestName' : IDL.Text,
    'message' : IDL.Text,
    'attending' : IDL.Bool,
    'guestPhone' : IDL.Text,
  });
  const UpdateEventInput = IDL.Record({
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'eventType' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Photo], []),
    'addPhotos' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func([EventInput], [Event], []),
    'createInvitation' : IDL.Func([InvitationInput], [Invitation], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'deleteInvitation' : IDL.Func([IDL.Text], [], []),
    'deletePhoto' : IDL.Func([IDL.Text], [], []),
    'deleteThemeVariant' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllInvitations' : IDL.Func([], [IDL.Vec(Invitation)], ['query']),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getBackgroundMusic' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BackgroundMusic)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEventsByInvitation' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
    'getInvitationBySlug' : IDL.Func([IDL.Text], [Invitation], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getPhotosByInvitation' : IDL.Func([IDL.Text], [IDL.Vec(Photo)], ['query']),
    'getRSVPsByInvitation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RSVPEntry)],
        ['query'],
      ),
    'getRSVPsStats' : IDL.Func([IDL.Text], [RSVPStats], ['query']),
    'getThemeVariants' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ThemeConfig)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishInvitation' : IDL.Func([IDL.Text], [Invitation], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveThemeVariant' : IDL.Func([IDL.Text, ThemeConfig], [], []),
    'setBackgroundMusic' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [BackgroundMusic],
        [],
      ),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'submitWeddingInvitationRSVP' : IDL.Func([RSVPInput], [RSVPEntry], []),
    'updateEvent' : IDL.Func([IDL.Text, UpdateEventInput], [Event], []),
    'updateInvitation' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Invitation],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };