/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BackgroundMusic {
  'id' : string,
  'musicUrl' : string,
  'autoPlay' : boolean,
  'invitationId' : string,
  'uploadedAt' : bigint,
}
export interface Event {
  'id' : string,
  'title' : string,
  'venue' : string,
  'date' : string,
  'invitationId' : string,
  'time' : string,
  'description' : string,
  'eventType' : EventType,
}
export type EventType = { 'mehndi' : null } |
  { 'sangeet' : null } |
  { 'haldi' : null } |
  { 'custom' : null } |
  { 'wedding' : null } |
  { 'reception' : null };
export interface Invitation {
  'id' : string,
  'weddingDate' : string,
  'invitationMessage' : string,
  'weddingTime' : string,
  'isPublished' : boolean,
  'venueAddress' : string,
  'createdAt' : bigint,
  'googleMapsLink' : string,
  'fontChoice' : string,
  'updatedAt' : bigint,
  'selectedTemplate' : string,
  'savedThemes' : Array<ThemeConfig>,
  'backgroundChoice' : string,
  'brideName' : string,
  'groomName' : string,
  'venueName' : string,
  'familyDetails' : string,
  'colorScheme' : string,
}
export interface Photo {
  'id' : string,
  'invitationId' : string,
  'imageUrl' : string,
  'uploadedAt' : bigint,
}
export interface RSVPEntry {
  'id' : string,
  'guestCount' : bigint,
  'invitationId' : string,
  'submittedAt' : bigint,
  'guestName' : string,
  'message' : string,
  'attending' : boolean,
  'guestPhone' : string,
}
export interface RSVPStats {
  'totalConfirmedGuests' : bigint,
  'totalResponses' : bigint,
  'totalDeclined' : bigint,
}
export interface ThemeConfig {
  'fontChoice' : string,
  'backgroundChoice' : string,
  'template' : string,
  'colorScheme' : string,
}
export interface _SERVICE {
  'addEvent' : ActorMethod<
    [string, string, string, string, string, string, string, EventType],
    Event
  >,
  'addPhoto' : ActorMethod<[string, string, string], Photo>,
  'createInvitation' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    Invitation
  >,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'deleteInvitation' : ActorMethod<[string], undefined>,
  'deletePhoto' : ActorMethod<[string], undefined>,
  'deleteThemeVariant' : ActorMethod<[string, bigint], undefined>,
  'getAllInvitations' : ActorMethod<[], Array<Invitation>>,
  'getBackgroundMusic' : ActorMethod<[string], Array<BackgroundMusic>>,
  'getEventsByInvitation' : ActorMethod<[string], Array<Event>>,
  'getInvitationBySlug' : ActorMethod<[string], Invitation>,
  'getPhotosByInvitation' : ActorMethod<[string], Array<Photo>>,
  'getRSVPsByInvitation' : ActorMethod<[string], Array<RSVPEntry>>,
  'getRSVPsStats' : ActorMethod<[string], RSVPStats>,
  'getThemeVariants' : ActorMethod<[string], Array<ThemeConfig>>,
  'publishInvitation' : ActorMethod<[string], Invitation>,
  'saveThemeVariant' : ActorMethod<[string, ThemeConfig], undefined>,
  'setBackgroundMusic' : ActorMethod<
    [string, string, string, boolean],
    BackgroundMusic
  >,
  'submitRSVP' : ActorMethod<
    [string, string, string, string, boolean, bigint, string],
    RSVPEntry
  >,
  'updateEvent' : ActorMethod<
    [string, string, string, string, string, string, EventType],
    Event
  >,
  'updateInvitation' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    Invitation
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];